### ISSUE TITLE
Silent Quit

### ISSUE THREAD

**Issue by dukedase** [MultiChat/Documentation#1]
Hello, people with the silentjoin permission join silently, but they don't leave silently.

**Comment by dukedase** [comment]
Also, when I promote or change someones group in LuckPerms it gives them both their old and new prefix, with the new one first.  It can be fixed by /server switching to another server and back

**Comment by OllieMartin** [comment]
Hi there! I will look into this as soon as I can, I did notice the issue of silent quitting not functioning correctly once before but I thought I had patched it! As for the luck perms thing, that seems slightly odd to me, I shall investigate! Sorry for the inconvenience.

Also please see my recent update to the plugin thread in case I take a while to fix this for you, my apologies! "Hello everyone! I am aware that there are currently some recurring bugs with the plugin that only seem to appear in specific situations. I am doing my best to look into these as soon as possible but I am the sole developer for this plugin in the middle of a university degree so my time is spread very thinly! I do sincerly apologise if I appear to be taking a long time to fix things up, I can assure you I will always do my best as I despise providing a service which does not operate perfectly for you all. In my spare time I get I will be looking at fixes as well as implementing all the features that I keep getting asked for, but of course I will prioritise fixing issues. Thankyou all for the great feedback on the plugin, I appreciate the support, and I hope to be pushing out the updates you all need soon!"

**Comment by OllieMartin** [comment]
Regarding the prefixes. Have you tried just getting them to send a single chat message? It usually takes this much for MultiChat to realise there has been a change and communicate it to bungeecord. I will keep looking for anything else, but in all my tests with LuckPerms it works fine after the first message has been sent. I am looking into ways to make it instantly change but this is more difficult as I will need to do a lot more complex processing.

**Comment by dukedase** [comment]
Yes, I've had them send many messages and wait up to 10 minutes with over 20 messages sent.  Only fixes upon switching servers.

**Comment by OllieMartin** [comment]
Here is a snapshot version of MultiChat 1.4 that I am in the process of developing, Ive had a go at refining some things, so please let me know if it fixes your problem.

If it doesnt then I will keep looking! It seems very weird that switching server would affect the way the prefix is displayed.

https://github.com/MultiChat/Development/blob/master/multichat/target/multichat-1.4.jar

**Comment by OllieMartin** [comment]
Hi, that above link has now been updated to an even newer version which I am 99% sure will fix the double prefix issue, and it SHOULD fix the silent leaving as well. Please let me know how it goes! :D

**Comment by dukedase** [comment]
Prefix issue seems to be fixed, but the silent leaving isn't working

**Comment by dukedase** [comment]
Also, this randomly happened:  Only thing that I can tell happened before it was someone connected right when I sent the message, but I tested that and couldn't replicate it.

https://i.gyazo.com/d4c9b4db5585e9ec88864caea72eeaf1.png

**Comment by OllieMartin** [comment]
Weird that the silent quit isnt working but the silent join is... Could you possibly send me a screenshot of when someone with the silentjoin permission quits and also your joinmessages config file. As for the random colour codes showing in chat I have never seen anything like that happen before! Do let me know if it happens again and in the mean time I will see if I can see anything that could cause it! The prefix showing in the essentials TP is actually intended as it is something that most chat plugins manage and mine wasn't doing before. But if its something you arent keen on I can easily just remove it since this is just a snapshot version. Either that or I could probably make a config option for it.

**Comment by dukedase** [comment]
When someone with perm leaves: https://i.gyazo.com/e8a62210a213652e5e0dc01d770fda56.mp4
The problem with the prefix thing showing up in other plugin announcements is it doesn't actually work, it shows the actual prefix IE instead of a red "Imperator" it says &f<&4Imperator&f> &4 Peratus" in the announcements

Config:  https://i.gyazo.com/1bdcf204361397841c9356d44b6d1702.png

**Comment by OllieMartin** [comment]
That is so weird, so the silent join works fine but quit doesnt?! I dont understand how thats even possible as they use the same permission node to check... I guess Ill have to do some more investigation.  And oh I see regarding the teleport etc, darn thats annoying, I shall see what I can do with that, if I cant get it to show the correct colours Ill just remove it

**Comment by OllieMartin** [comment]
Hey, can I just check the perm node you have for silent join? As I think in the past there was an older one and i just want to make sure its right. Also, Im going to put together a JAR with debug messages so you can send me the logs afterwards and hopefully Ill be able to figure out why the quitting isnt working properly :)

**Comment by OllieMartin** [comment]
https://github.com/MultiChat/Development/blob/master/multichat/DebugVersions/MultiChat%201.4%20SilentJoinAndQuit%20DEBUG%20VERSION.jar

**Comment by dukedase** [comment]
I assume https://i.gyazo.com/9e7178522cd47f507b3d7b5621833613.png is what you need

The permission I have is https://i.gyazo.com/ee0811c9466a8fc2c78ba864c4cd39de.png

**Comment by OllieMartin** [comment]
Yes thats perfect thankyou! I'm amazed at what it says there though as it says you dont have permission while logging out, but that you do while logging in, and considering I have double checked the code about 10 times to make sure I didnt get a typo in the perm node or something I dont see how its possible! I am having a go myself again to try and duplicate the issue, thanks for the help and patience :)

**Comment by OllieMartin** [comment]
I just ran that exact jar myself, gave myself only the multichat.staff.silentjoin permission and tried logging in and out and it works for me... Im using BungeePerms atm though not LuckPerms so Im going to install luckperms and try it with that in case it makes a difference. I guess there could be some thing where luckperms essentially removes players permissions as they logout.

**Comment by dukedase** [comment]
I have VanishNoPacket installed on one of the servers and it works fine with silently quitting

**Comment by OllieMartin** [comment]
Okay I finally managed to re-create the issue now that Luckperms is up and running, I think I have an idea what could be up so Im going to try and fix it now if its what I think it is :)

**Comment by OllieMartin** [comment]
Hurrah! It works for me so I can only hope it works for you too :)

https://github.com/MultiChat/Development/blob/master/multichat/Versions/1.4/1.4.0/Snapshots/MultiChat%201.4%20Snapshot%206.jar

**Comment by dukedase** [comment]
That does indeed fix it!  Thank you!

**Comment by OllieMartin** [comment]
No problem! Im glad to be of assistance! And thankyou for bringing the issue to my attention :)
