### ISSUE TITLE
Prefixes and Suffixes

### ISSUE THREAD

**Issue by Galadriel1640** [MultiChat/Documentation#2]
Hey I just downloaded and installed MultiChat!  I am currently facing an issue where MultiChat seems to not connect with LuckPerms which I thought was compatible?  Is this not true or have I missed a config option?  I am running a SpongeForge server with LuckPerms and Nucleus connected to a 1.12 Spigot server also using LuckPerms, but also has EssentialsxChat (your plugin seems to connect to that singular plugin and force the other servers to inherit those prefixes) and have it all connected with BungeeCord with MultiChat in the plugins folder of each server, including the proxy.  I made sure to also have it fetch server names.  Any ideas why the Sponge server wont keep its own prefixes?  - I did test this with gChat as a global chat alternative and it did keep the names proper, however it seems to lack any form of global chat.

**Comment by Galadriel1640** [comment]
I reinstalled everything fresh and it no longer prioritizes the Essentials plugin, but I still cannot get it to work on my SpongeForge server so it may be my Nucleus config after all.  You can probably close this issue, unless you have had someone else with this issue and know what I did wrong :)

**Comment by Galadriel1640** [comment]
Did some testing with the Nucleus dev and messed around with some configs; seeing as it only doesn't work on the sponge server, we are thinking it may just be multichat not reading sponge displaynames correctly?  I am using the latest version of MultiChat and 1.10.2 latest sponge, by the way

**Comment by Tom-III** [comment]
I have the same issue, I can't see my prefixes or suffixes, sometimes randomly they show up then when I like restart the server or add/remove a prefix it all breaks and I have no idea how to get them back...

**Comment by Galadriel1640** [comment]
I've talked to several devs about this and a few server owners. The only "fix" that supposedly works is using an earlier version or just flat out using the proxy to hold all permissions rather than the individual servers. I never got around to testing that, however, ended up getting rid of bungee and getting a custom plugin to do cross server chat XD if that's all you need, look into PurpleIRC if you have a few bucks to spend on an IRC server, and if you don't, there are other plugins that don't need a proxy or IRC, they are just harder to find....

**Comment by OllieMartin** [comment]
Hi there,

I realise that this was a very long time ago so you may no longer require help, but I am going through all of these bug reports anyway. Apologies for the long wait time but as I’ve said in the spigot thread recently, I have sadly just had little to no free time to contribute to the plugin. 

———————

As far as I know this is no longer an issue. I personally am not an avid user of sponge, but appreciated that lots of people required this functionality so was more that happy to support sponge severs. But it means that often I neglect to check sponge when doing updates etc. I have recently updated the plugin to 1.13 but again must Admin I haven’t touched the sponge side for a while. I shall make a point of taking a look to see if it’s all working as intended, and if not I will make it a priority to fix :)

**Comment by Galadriel1640** [comment]
Hey there!

I’m actually working on updating to 1.13 as soon as the spigot build is stable, so I’ll be needing a new chat plugin! I thank you for coming back and working on this, I shall report if I have issues again :)

**Comment by OllieMartin** [comment]
Hi there,

I believe there may have been issues with sponge on the 1.5.1 version, but I have now made some changes and am about to release 1.5.2 which I have tested on Sponge (and it seems to work fine for me now :) )

**Comment by Galadriel1640** [comment]
Beautiful, thanks so much! I’ll test it for myself as soon as I can! Thank you for workouts my on it!
