### ISSUE TITLE
pass chat to server

### ISSUE THREAD

**Issue by Behoston** [MultiChat/Documentation#3]
there is any option to send chat to server? I need to use it in denizen scripts...

**Comment by michaeldriskell** [comment]
Local chat should be handled each individual server.. I have quests and a plugin for redeeming mcmmo points and both receive messages that wont receive them when I have Multichat. BungeeChat has a "send messages to server" option but it duplicates the messages. Multichat should have an option to send messages to the server. Since you have to install a plugin on each spigot server for multichat I dont see how this couldnt be done... Good luck. :)

**Comment by Behoston** [comment]
I use IRC on each individual server instead of bungee plugin, it looks ugly now but 100% works (msg between servers is little bit harder for user but still is possible)

**Comment by OllieMartin** [comment]
Hi there,

I realise that this was a very long time ago so you may no longer require help, but I am going through all of these bug reports anyway. Apologies for the long wait time but as I’ve said in the spigot thread recently, I have sadly just had little to no free time to contribute to the plugin. 

—-

As has been started here, this is a difficult issue. Bungeecord chat plugins are entirely incompatible with spigot / bukkit / sponge chat plugins. The chat has to be handled by bungeecord FIRST before it goes to spigot. So there is basically no way for bungee plugins to let spigot handle it first and then go back to it after. It may be a possibility to add a “send to server” option, but this will not fix everything, and yes will likely cause duplication with some plugins. 

I can think of a possible way around this but it is complicated and I don’t think I have enough time to do it right now. But I do appreciate this is an annoying complication with bungeecord. I will do my best to devise a solution in the future. In the mean time all I can suggest is making servers where this is vital functionality separated from the global chat, as they will default to their locally handled chat.

Again, I realise this is likely no longer revelvant but I am making a point of closing all these old issues!

Thanks a lot,
Revilo
