### ISSUE TITLE
Feature Request: Automatic Broadcasts

### ISSUE THREAD

**Issue by MothGirlMusic** [MultiChat/Documentation#6]
**What is it?**

Automatic Broadcasts are messages that are automatically broadcasted over the network. There will be a list of broadcasts in a text file. the config will have the time between broadcasts. ie: 300 for 5 minutes between each broadcast. the broadcast will choose a random line and broadcast it. every 300 seconds. this can be help tips, advertisements... and players could even pay for "temporary broadcasts" with vault. a temporary broadcast would only be in the broadcasts list until it "expires" by either having been broadcasted a specific number of times, or from it being in the broadcast file for a set amount of time. the former would probably be both easier to program and also more exact for the player to know what kind of advertisement they're buying with in-game money... why would they do that? for shops, faction recruiting, towny recruiting... maybe they've got a minigame like a parkour course or a build they would like people to visit or vote on to win a contest... be voted mayor or king of a city or country in towny... there's loads of plugs that this could be useful for and i believe a chat & broadcast plugin like this would be where this type of feature would be best implemented.

**How would I implement the commands?**

`/acast add This is an automatic broadcast! This line gets added to the autocast.txt file!`

`/acast buy [number of bcasts] [message]`
Aliases of "/acast buy": /promote, /advert, /advertise

acast buy messages would be in "adverts.txt" and would be formatted as such:
`#:Message`
where the # is the amount of times broadcasted it has left. if its a 1 it would broadcast and delete the line. if its a 0 or anything less than 1, it would delete the line without broadcasting.

I truely hope this can be added, as i believe it would be a very nice feature for survival servers and other large network servers with minigames, factions, towny, and other alike plugins. I believe it could be a very big feature to post about and boost your downloads as this would be one of the few useful features no one has in their chatplugins, bungee or otherwise.
- Moth

**Comment by OllieMartin** [comment]
Hi there,

Sorry for the slow reply, as I have stated on the spigot page many times recently I have had so little free time to dedicate to the plugin.

I will be releasing some smaller updates to the plugin in the coming months and will endeavour to add requested features such as this. I will let you know when / if I manage to add it :)

I’m not sure if you have used the “bulletins” feature in the plugin already but it is very similar to this. What you are describing is just a much more powerful version. I’d be more than happy to see how I could incorporate this into the plugin :)

**Comment by OllieMartin** [comment]
I am closing this issue, but have it noted for the future updates :)
